Add dependency to sqlite3
including sqlite3.h is required instead of db-util.h at bluetooth-share-api.h
bluetooth-share-api exports sqlite3(in past, db-util.h) in its header
but it doesn't have dependency to sqlite3

[  229s]
/home/abuild/rpmbuild/BUILD/bluetooth-share-0.0.47/lib/bluetooth-share-api.h:27:21:
fatal error: db-util.h: No such file or directory

Change-Id: I7650a7c9e2d2e04ad61204dc26642889401c950f
Signed-off-by: Sangyoon Jang <s89.jang@samsung.com>